services:
  - type: web
    name: pix-spectrum-backend
    env: python
    region: oregon
    plan: free
    rootDir: BackEnd
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: VITE_APP_FOO
        value: "https://pixspectrum-2.onrender.com/"
